### PR TITLE
Fix SpinReversalTransformComposite's behavior when child samplers change the variable order

### PR DESCRIPTION
**Pull request by arcondello**
Closes https://github.com/dwavesystems/dwave-preprocessing/issues/142
See also https://github.com/dwavesystems/dwave-system/issues/538

### CODE REVIEW

**Comment by arcondello** [comment]
CI errors unrelated. Will fix.

**Review by jackraymond — APPROVED** [review]
Code looked good, running tests and original bug report code.

**Comment by arcondello** [comment]
The following test still fails. Will fix...
```python
    def test_variable_order2(self):
        class GroundStateSampler:
            @staticmethod
            def sample(bqm):
                return dimod.ExactSolver().sample(bqm).lowest()

        bqm = dimod.BinaryQuadraticModel(
            {}, {(1, 0): 0, (4, 3): 0, (2, 0): -1, (2, 1): 1, (5, 3): -1, (5, 4): 1}, 0, 'SPIN')

        sampler = SpinReversalTransformComposite(GroundStateSampler(), seed=42)

        sampleset = sampler.sample(bqm, num_spin_reversal_transforms=10)

        self.assertEqual(len(sampleset.aggregate()), 4)
```

**Comment by jackraymond** [comment]
Checking that sampleset variable order matches bqm variable order is always recommended. A sampleset can be forced to match the bqm order using: `ss = dimod.SampleSet.from_samples_bqm(ss, bqm)`

**Pull request merged**
